// Copyright (c) 2023-2024 Percona and/or its affiliates.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License, version 2.0,
// as published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License, version 2.0, for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA

#include "operations/event_generation_helpers.hpp"

#include <cstdint>

#include "binsrv/events/checksum_algorithm_type.hpp"
#include "binsrv/events/code_type.hpp"
#include "binsrv/events/common_header_flag_type.hpp"
#include "binsrv/events/composite_binlog_name_fwd.hpp"
#include "binsrv/events/event.hpp"
#include "binsrv/events/event_view.hpp"
#include "binsrv/events/protocol_traits_fwd.hpp"
#include "binsrv/events/reader_context.hpp"

#include "binsrv/gtids/gtid_set_fwd.hpp"

#include "util/ctime_timestamp.hpp"
#include "util/semantic_version.hpp"

namespace operations {

void generate_rotate_event_ex(
    binsrv::events::event_storage &event_buffer, bool include_checksum,
    std::uint32_t offset, bool current_timestamp, std::uint32_t server_id,
    bool artificial, const binsrv::events::composite_binlog_name &binlog_name,
    std::uint64_t position) {
  const binsrv::events::generic_post_header<binsrv::events::code_type::rotate>
      post_header{position};
  const binsrv::events::generic_body<binsrv::events::code_type::rotate> body{
      binlog_name};

  util::ctime_timestamp timestamp{};
  if (current_timestamp) {
    timestamp = util::ctime_timestamp::now();
  }

  binsrv::events::common_header_flag_set flags{};
  if (artificial) {
    flags |= binsrv::events::common_header_flag_type::artificial;
  }

  const auto generated_event{
      binsrv::events::event::create_event<binsrv::events::code_type::rotate>(
          offset, timestamp, server_id, flags, post_header, body,
          include_checksum, event_buffer)};
}

[[nodiscard]] binsrv::events::event_view
generate_rotate_event(binsrv::events::event_storage &event_buffer,
                      const binsrv::events::reader_context &context,
                      std::uint32_t offset, bool current_timestamp,
                      std::uint32_t server_id, bool artificial,
                      const binsrv::events::composite_binlog_name &binlog_name,
                      std::uint64_t position) {

  // the value of the 'include_checksum' parameters is taken from the
  // 'reader_context': immediately after reconnection it will be equal to
  // the '<replication.verify_checksum>' configuration parameter and after
  // that will be taken from the FORMAT_DESCRIPTION events, which in the
  // rewrite mode will be generated by us and therefore will always include
  // 'checksum_algorithm' set to 'crc32'
  generate_rotate_event_ex(event_buffer, context.is_footer_expected(), offset,
                           current_timestamp, server_id, artificial,
                           binlog_name, position);

  return binsrv::events::event_view{context,
                                    util::const_byte_span{event_buffer}};
}

void generate_format_description_event_ex(
    binsrv::events::event_storage &event_buffer,
    const util::semantic_version &server_version, std::uint32_t offset,
    std::uint32_t server_id, bool enable_checksum_algorithm, bool artificial) {
  const binsrv::events::generic_post_header<
      binsrv::events::code_type::format_description>
      post_header{
          binsrv::events::default_binlog_version, server_version,
          artificial ? util::ctime_timestamp{} : util::ctime_timestamp::now(),
          binsrv::events::default_common_header_length,
          binsrv::events::reader_context::get_hardcoded_post_header_lengths(
              server_version.get_encoded())};

  const auto checksum_algorithm{
      enable_checksum_algorithm ? binsrv::events::checksum_algorithm_type::crc32
                                : binsrv::events::checksum_algorithm_type::off};

  const binsrv::events::generic_body<
      binsrv::events::code_type::format_description>
      body{checksum_algorithm};

  // here we set the 'artificial' flag for the common header only as a marker
  // for 'event::create_event<>()' - that function will make a decision
  // whether to set 'next_event_position' to 0 based on this flag but will
  // clear it out before serialization
  binsrv::events::common_header_flag_set flags{};
  if (artificial) {
    flags |= binsrv::events::common_header_flag_type::artificial;
  }

  // FORMAT_DESCRIPTION events always include a checksum
  const auto generated_event{binsrv::events::event::create_event<
      binsrv::events::code_type::format_description>(
      offset, util::ctime_timestamp::now(), server_id, flags, post_header, body,
      true /* include_checksum */, event_buffer)};
}
[[nodiscard]] binsrv::events::event_view generate_format_description_event(
    binsrv::events::event_storage &event_buffer,
    const binsrv::events::reader_context &context, std::uint32_t offset,
    std::uint32_t server_id, bool enable_checksum_algorithm, bool artificial) {
  const util::semantic_version server_version{
      context.get_current_encoded_server_version()};
  // enforcing checksums for all rewritten upcoming events
  generate_format_description_event_ex(event_buffer, server_version, offset,
                                       server_id, enable_checksum_algorithm,
                                       artificial);

  return binsrv::events::event_view{context,
                                    util::const_byte_span{event_buffer}};
}

[[nodiscard]] binsrv::events::event_view
generate_previous_gtids_log_event(binsrv::events::event_storage &event_buffer,
                                  const binsrv::events::reader_context &context,
                                  std::uint32_t offset, std::uint32_t server_id,
                                  const binsrv::gtids::gtid_set &gtids) {
  const binsrv::events::generic_post_header<
      binsrv::events::code_type::previous_gtids_log>
      post_header{};
  const binsrv::events::generic_body<
      binsrv::events::code_type::previous_gtids_log>
      body{gtids};
  const auto generated_previous_gtids_log_event{
      binsrv::events::event::create_event<
          binsrv::events::code_type::previous_gtids_log>(
          offset, util::ctime_timestamp::now(), server_id,
          binsrv::events::common_header_flag_set{}, post_header, body, true,
          event_buffer)};

  return binsrv::events::event_view{context,
                                    util::const_byte_span{event_buffer}};
}

} // namespace operations
